### ISSUE TITLE
Search Location not working.

### ISSUE THREAD

**Issue by TommyNesset** [heldersepu/GMapCatcher#454] opened 2018-05-08 09:11 UTC
When searching for a location, i keep getting "Location <location> not found" ("Location New York not found")
I've tried with the following map Services: Nokia, Google, OpenSteetMap, CloudMade, OpenCycleMap and Maps-For-Free

**Comment by heldersepu** [comment] 2018-05-08 11:40
Duplicate of #451
Unfortunately the search uses google for all services

**Closed by heldersepu** 2018-05-08 11:40 UTC
