### ISSUE TITLE
SLLContext error

### ISSUE THREAD

**Issue by GISConsortium** [heldersepu/GMapCatcher#446] opened 2017-11-10 10:32 UTC
While running maps.py I am getting below error :

'module' object has no attribute 'SSLContext''module' object has no attribute 'SSLContext'

Help will be appreciated.

Regards,
Kranti

**Comment by heldersepu** [comment] 2017-11-10 12:53
Do you have a clean version of GMapCatcher or have you been making modifications?
I do not get such an error

**Comment by heldersepu** [comment] 2017-11-10 13:21
I'm closing this issue due to lack of details...
Please provide exact steps to reproduce the issue

**Closed by heldersepu** 2017-11-10 13:21 UTC

**Comment by GISConsortium** [comment] 2017-11-13 03:55
I have not done any modifications on the code. But I am not sure about the clean version of GMapCatcher.
Can you please share if you have.

**Comment by heldersepu** [comment] 2017-11-13 12:43
If you have not done any modifications on the code. you should have a clean version...
Please provide exact steps to reproduce your issue

**Comment by GISConsortium** [comment] 2017-11-14 09:29
I have downloaded your clean version from your post and now it is working as expected, Thanks.

Can you let me know where you have functionality to load the KML files in your GUI.

**Comment by heldersepu** [comment] 2017-11-14 13:08
the load KML is very very basic
and the dialog to load the file opens when you hit F4 

Here is a link to the user guide:
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md#keyboard-shortcuts

**Comment by GISConsortium** [comment] 2017-11-14 13:46
Appreciated. Thanks.

**Comment by GISConsortium** [comment] 2017-11-14 13:55
Can you share any KML sample to test it. We need to know the format.

Thanks.

**Comment by heldersepu** [comment] 2017-11-14 14:05
Sorry I searched I don't have any KML files in my drive anymore...
But looking at the code:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/xmlUtils.py#L5
It gets the Placemark tags in the KML file

**Comment by heldersepu** [comment] 2017-11-14 14:25
[Battles.zip](https://github.com/heldersepu/GMapCatcher/files/1471127/Battles.zip)
I found one file it adds a bunch of markers in South Africa

**Comment by GISConsortium** [comment] 2017-11-15 09:10
Thanks. It is loading map.

**Comment by GISConsortium** [comment] 2017-11-30 03:39
Hi Helder,

I am trying to add new panel left to the scale box and want to resize map panel. Could you please help in this.

Thanks

**Comment by heldersepu** [comment] 2017-11-30 03:41
Email me directly...

**Comment by GISConsortium** [comment] 2017-11-30 03:55
Sent it.

**Comment by GISConsortium** [comment] 2017-12-08 13:57
Hi Helder,

Can you please let me know how to load KML on OpenStreetMap? This KML is having polygon coordinates

In your current code example, you are adding point kml to google map.

Thanks

**Comment by heldersepu** [comment] 2017-12-08 14:00
Load KML on OpenStreetMap ?!?!
what does that has to do with this project?

**Comment by heldersepu** [comment] 2017-12-08 14:04
Email me directly...

**Comment by GISConsortium** [comment] 2017-12-08 14:07
Mail sent
